### ISSUE TITLE
Issues with readUCI and readHBN tools

### ISSUE THREAD

**Issue by steveskrip** [LimnoTech/HSPsquared#16]
I attempted to validate three of the [standard HSPF tests from the Respec FORTRAN GitHub repository](https://github.com/respec/FORTRAN/tree/master/test/hspf/standard/Current), as suggested by  @PaulDudaRESPEC in https://github.com/respec/HSPsquared/issues/31#issuecomment-687137982.

I had issues with each one using the HSP2 tools. These are documented in the [test10_compare](https://github.com/LimnoTech/HSPsquared/tree/test10_compare) branch.

### test10 (`/HSPsquared/tests/test10b`)
 - could not successfully run test10.uci as provided in the HSP2 test directory in HSPF. Used test10.uci and test.wdm from Respec FORTRAN GitHub repository and successfully ran simulation in HSPF.
 - modified .uci to create .hbn binary output file and ran successfully in HSPF
 - `HSPsquared/tests/test10b/HSPFresults/test10.hbn` file can be read in BASINS timeseries plugin and makes sense
 - HSPsquared/tests/test10b/HSPFresults/Run HSPF.ipynb, readHBN(hbnname,HBN) returns with the following error 
 

```
ALIGNMENT ERROR ERLND
UNKNOW RECTYPE 1342177280
```

and only two records returned
 
 
### test05 (`/HSPsquared/tests/test05`)
 - modified .uci to create .hbn binary output file
 - readHBN successfully executed in `HSPsquared/tests/test05/HSPFresults/Run HSPF.ipynb`
 - error when executing readUCI(uciname, hdfname) in `HSPsquared/tests/test05/HSP2compare/CompareHSP2.ipynb`. Same error occurs when reading` test05.uci`, original test file.
 
```
 ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-96d75fe5d884> in <module>
----> 1 readUCI(uciname, hdfname)
      2 readWDM(wdmname, hdfname)

c:\Users\sskripnik\Documents\GitHub\HSPsquared\HSP2tools\readUCI.py in readUCI(uciname, hdfname)
    120             if line[0:9] == 'MASS-LINK':   masslink(info, getlines(f))
    121             if line[0:7] == 'FTABLES':      ftables(info, getlines(f))
--> 122             if line[0:3] == 'EXT':              ext(info, getlines(f))
    123             if line[0:6] == 'PERLND':     operation(info, getlines(f),'PERLND')
    124             if line[0:6] == 'IMPLND':     operation(info, getlines(f),'IMPLND')

c:\Users\sskripnik\Documents\GitHub\HSPsquared\HSP2tools\readUCI.py in ext(info, lines)
    308         del dfext['TOPFST']
    309         del dfext['TOPLST']
--> 310         dfext = dfext.sort_values(by=['TVOLNO'])
    311         dfext.to_hdf(store, '/CONTROL/EXT_SOURCES', data_columns=True)
    312 

~\Anaconda3\envs\hsp2_py37\lib\site-packages\pandas\core\frame.py in sort_values(self, by, axis, ascending, inplace, kind, na_position, ignore_index)
   4925 
   4926             by = by[0]
-> 4927             k = self._get_label_or_level_values(by, axis=axis)
   4928 
   4929             if isinstance(ascending, (tuple, list)):

~\Anaconda3\envs\hsp2_py37\lib\site-packages\pandas\core\generic.py in _get_label_or_level_values(self, key, axis)
   1690             values = self.axes[axis].get_level_values(key)._values
   1691         else:
-> 1692             raise KeyError(key)
   1693 
   1694         # Check for duplicates

KeyError: 'TVOLNO'
```
 
 
### test09 ( HSPsquared/tests/test09)
 - modified .uci to create .hbn binary output file
 - readHBN successfully executed in `HSPsquared/tests/test09/HSPFresults/Run HSPF.ipynb`
 - error when executing readUCI(uciname, hdfname) in `HSPsquared/tests/test09/HSP2compare/CompareHSP2.ipynb`. Same error occurs when reading `test09.uci`, original test file.
```
 ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-96d75fe5d884> in <module>
----> 1 readUCI(uciname, hdfname)
      2 readWDM(wdmname, hdfname)

c:\Users\sskripnik\Documents\GitHub\HSPsquared\HSP2tools\readUCI.py in readUCI(uciname, hdfname)
    116             if line[0:6] == 'GLOBAL':       global_(info, getlines(f))
    117             if line[0:3] == 'OPN':              opn(info, getlines(f))
--> 118             if line[0:7] == 'NETWORK':  net=network(info, getlines(f))
    119             if line[0:9] == 'SCHEMATIC':sc=schematic(info,getlines(f))
    120             if line[0:9] == 'MASS-LINK':   masslink(info, getlines(f))

c:\Users\sskripnik\Documents\GitHub\HSPsquared\HSP2tools\readUCI.py in network(info, lines)
    236         if d['SVOL'] in ops and d['TVOL'] in ops:
    237             d['SVOLNO'] = f"{d['SVOL'][0]}{int(d['SVOLNO']):03d}"
--> 238             d['TVOLNO'] = f"{d['TVOL'][0]}{int(d['TVOLNO']):03d}"
    239             lst.append(d)
    240     return DataFrame(lst, columns=d) if lst else DataFrame()

KeyError: 'TVOLNO'
```

**Comment by aufdenkampe** [comment]
@steveskrip, thank you for trying to run the standard HSPF tests that @PaulDudaRESPEC suggested in his comment to [respect #31: Expand & automate testing system](https://github.com/respec/HSPsquared/issues/31#issuecomment-687137982)!

Hopefully, @rheaphy can figure out and fix these read errors.

We have 3 related issues on this topic, which is relevant to Respec's efforts, so I suggest we try to move the conversation over to [respec #40: Improve readUCI for a broader range of valid UCI files](https://github.com/respec/HSPsquared/issues/40).

Meanwhile I'll close our [Import issue in readUCI #9](https://github.com/LimnoTech/HSPsquared/issues/9) because it appears that @rheaphy fixed that particular set of issues.

**Comment by PaulDudaRESPEC** [comment]
I just committed a change to ReadUCI (on the develop-WaterQuality branch) that fixes an issue with the Network Block.  It appears to resolve the issue you're having with Test09, and probably Test05 too.

**Comment by aufdenkampe** [comment]
Thanks @PaulDudaRESPEC!

@steveskrip, here's the commit: https://github.com/respec/HSPsquared/commit/e251cb1cf4001e45887c6de2323be648a13ab7d3

**Comment by aufdenkampe** [comment]
@steveskrip, let's move this conversation, with your latest results, over to https://github.com/respec/HSPsquared/issues/40.

**Comment by aufdenkampe** [comment]
Closing along with https://github.com/respec/HSPsquared/issues/40.
